
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniela
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
//ReteteForm retete=new ReteteForm();
    public NewJFrame() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        aragazCheck = new javax.swing.JCheckBox();
        cuptorCheck = new javax.swing.JCheckBox();
        tigaieCheck = new javax.swing.JCheckBox();
        bolCheck = new javax.swing.JCheckBox();
        mixerCheck = new javax.swing.JCheckBox();
        tocatorCheck = new javax.swing.JCheckBox();
        merdeneaCheck = new javax.swing.JCheckBox();
        blenderCheck = new javax.swing.JCheckBox();
        robotdebucatarieCheck = new javax.swing.JCheckBox();
        paletaCheck = new javax.swing.JCheckBox();
        tavaCheck = new javax.swing.JCheckBox();
        telCheck = new javax.swing.JCheckBox();
        vegetarianImg = new javax.swing.JLabel();
        cardiacImg = new javax.swing.JLabel();
        diabetImg = new javax.swing.JLabel();
        infometatImg = new javax.swing.JLabel();
        intervaltimpSlider = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        diabeticRad = new javax.swing.JRadioButton();
        vegetarianRad = new javax.swing.JRadioButton();
        cardiacRad = new javax.swing.JRadioButton();
        niciopreferintaRad = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaingrediente = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        next2Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        minute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        textaratareteta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        girl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aratareteteBtn = new javax.swing.JButton();
        next3Btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        clientLogat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(60767, 60767));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        aragazCheck.setBackground(new java.awt.Color(255, 255, 255));
        aragazCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        aragazCheck.setForeground(new java.awt.Color(102, 102, 0));
        aragazCheck.setText("aragaz");

        cuptorCheck.setBackground(new java.awt.Color(255, 255, 255));
        cuptorCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        cuptorCheck.setForeground(new java.awt.Color(102, 102, 0));
        cuptorCheck.setText("cuptor");

        tigaieCheck.setBackground(new java.awt.Color(255, 255, 255));
        tigaieCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tigaieCheck.setForeground(new java.awt.Color(102, 102, 0));
        tigaieCheck.setText("tigaie");

        bolCheck.setBackground(new java.awt.Color(255, 255, 255));
        bolCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        bolCheck.setForeground(new java.awt.Color(102, 102, 0));
        bolCheck.setText("bol");

        mixerCheck.setBackground(new java.awt.Color(255, 255, 255));
        mixerCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        mixerCheck.setForeground(new java.awt.Color(102, 102, 0));
        mixerCheck.setText("mixer");
        mixerCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixerCheckActionPerformed(evt);
            }
        });

        tocatorCheck.setBackground(new java.awt.Color(255, 255, 255));
        tocatorCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tocatorCheck.setForeground(new java.awt.Color(102, 102, 0));
        tocatorCheck.setText("tocator");

        merdeneaCheck.setBackground(new java.awt.Color(255, 255, 255));
        merdeneaCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        merdeneaCheck.setForeground(new java.awt.Color(102, 102, 0));
        merdeneaCheck.setText("merdenea");
        merdeneaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merdeneaCheckActionPerformed(evt);
            }
        });

        blenderCheck.setBackground(new java.awt.Color(255, 255, 255));
        blenderCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        blenderCheck.setForeground(new java.awt.Color(102, 102, 0));
        blenderCheck.setText("blender");

        robotdebucatarieCheck.setBackground(new java.awt.Color(255, 255, 255));
        robotdebucatarieCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        robotdebucatarieCheck.setForeground(new java.awt.Color(102, 102, 0));
        robotdebucatarieCheck.setText("robot de bucatarie");
        robotdebucatarieCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robotdebucatarieCheckActionPerformed(evt);
            }
        });

        paletaCheck.setBackground(new java.awt.Color(255, 255, 255));
        paletaCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        paletaCheck.setForeground(new java.awt.Color(102, 102, 0));
        paletaCheck.setText("paleta");

        tavaCheck.setBackground(new java.awt.Color(255, 255, 255));
        tavaCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tavaCheck.setForeground(new java.awt.Color(102, 102, 0));
        tavaCheck.setText("tava");

        telCheck.setBackground(new java.awt.Color(255, 255, 255));
        telCheck.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        telCheck.setForeground(new java.awt.Color(102, 102, 0));
        telCheck.setText("tel");
        telCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuptorCheck)
                            .addComponent(tigaieCheck)
                            .addComponent(bolCheck)
                            .addComponent(mixerCheck)
                            .addComponent(aragazCheck))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(tocatorCheck)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telCheck)
                    .addComponent(merdeneaCheck)
                    .addComponent(tavaCheck)
                    .addComponent(paletaCheck)
                    .addComponent(robotdebucatarieCheck)
                    .addComponent(blenderCheck))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aragazCheck)
                    .addComponent(merdeneaCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuptorCheck)
                    .addComponent(blenderCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tigaieCheck)
                    .addComponent(robotdebucatarieCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bolCheck)
                    .addComponent(paletaCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mixerCheck)
                    .addComponent(tavaCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tocatorCheck)
                    .addComponent(telCheck)))
        );

        vegetarianImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vegeta!!.png"))); // NOI18N

        diabetImg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        diabetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthyburger.png"))); // NOI18N
        diabetImg.setText("jLabel7");
        diabetImg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        intervaltimpSlider.setBackground(new java.awt.Color(255, 255, 255));
        intervaltimpSlider.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        intervaltimpSlider.setForeground(new java.awt.Color(0, 204, 204));
        intervaltimpSlider.setMajorTickSpacing(10);
        intervaltimpSlider.setPaintLabels(true);
        intervaltimpSlider.setPaintTicks(true);
        intervaltimpSlider.setValue(0);
        intervaltimpSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intervaltimpSliderStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        diabeticRad.setBackground(new java.awt.Color(255, 255, 255));
        diabeticRad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        diabeticRad.setForeground(new java.awt.Color(153, 0, 153));
        diabeticRad.setText("Diabetic");
        diabeticRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabeticRadActionPerformed(evt);
            }
        });

        vegetarianRad.setBackground(new java.awt.Color(255, 255, 255));
        vegetarianRad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        vegetarianRad.setForeground(new java.awt.Color(153, 0, 153));
        vegetarianRad.setText("Vegetarian");
        vegetarianRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetarianRadActionPerformed(evt);
            }
        });

        cardiacRad.setBackground(new java.awt.Color(255, 255, 255));
        cardiacRad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        cardiacRad.setForeground(new java.awt.Color(153, 0, 153));
        cardiacRad.setText("Cardiac");
        cardiacRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardiacRadActionPerformed(evt);
            }
        });

        niciopreferintaRad.setBackground(new java.awt.Color(255, 255, 255));
        niciopreferintaRad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        niciopreferintaRad.setForeground(new java.awt.Color(153, 0, 153));
        niciopreferintaRad.setText("Doar infometaaat");
        niciopreferintaRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niciopreferintaRadActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Urdu Typesetting", 1, 15)); // NOI18N
        jLabel4.setText("1. Esti ...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardiacRad)
                    .addComponent(vegetarianRad)
                    .addComponent(diabeticRad)
                    .addComponent(niciopreferintaRad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diabeticRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vegetarianRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardiacRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(niciopreferintaRad))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBar(null);

        listaingrediente.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        listaingrediente.setForeground(new java.awt.Color(0, 0, 102));
        listaingrediente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ciocolata", "frisca", "oua", "faina", "zahar", "smantana", "lamaie", "castravete", "rosie", "ardei", "mozzarella", "cascaval", "branza", "carne de pui", "carne de peste", "carne de porc", "carne de vita", "nicio preferinta" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaingrediente.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(listaingrediente);
        listaingrediente.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Urdu Typesetting", 1, 15)); // NOI18N
        jLabel3.setText("2. Ingredientele  principale...");

        next2Btn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        next2Btn.setForeground(new java.awt.Color(153, 153, 0));
        next2Btn.setText("Next ->");
        next2Btn.setBorderPainted(false);
        next2Btn.setContentAreaFilled(false);
        next2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2BtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("0");

        minute.setFont(new java.awt.Font("Urdu Typesetting", 1, 15)); // NOI18N
        minute.setText("min");
        minute.setToolTipText("");
        minute.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText(" Ce bunatati pregatesti astazi?");

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Sunt Chef Alice si te voi ajuta sa prepari delicatese inedite.");

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText(" Am cateva sugestii pentru tine; ce spui?");

        nextBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(153, 153, 0));
        nextBtn.setText("Next ->");
        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        textaratareteta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(255, 255, 255)));
        textaratareteta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textarataretetaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Urdu Typesetting", 1, 15)); // NOI18N
        jLabel7.setText("3.Ai  la dispozitie ");

        girl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/girl.jpg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Urdu Typesetting", 1, 15)); // NOI18N
        jLabel8.setText("4.Vei  folosi...");

        aratareteteBtn.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aratareteteBtn.setForeground(new java.awt.Color(153, 153, 0));
        aratareteteBtn.setText("Arata Retete");
        aratareteteBtn.setBorderPainted(false);
        aratareteteBtn.setContentAreaFilled(false);
        aratareteteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aratareteteBtnMouseClicked(evt);
            }
        });
        aratareteteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aratareteteBtnActionPerformed(evt);
            }
        });

        next3Btn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        next3Btn.setForeground(new java.awt.Color(153, 153, 0));
        next3Btn.setText("Next ->");
        next3Btn.setBorderPainted(false);
        next3Btn.setContentAreaFilled(false);
        next3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next3BtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("AngsanaUPC", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Sa incepem!");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(next2Btn)
                                    .addGap(103, 103, 103)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textaratareteta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addComponent(girl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nextBtn)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minute, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(next3Btn))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(intervaltimpSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(aratareteteBtn)
                                .addGap(90, 90, 90)))
                        .addComponent(diabetImg, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardiacImg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infometatImg, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vegetarianImg))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(clientLogat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(girl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton1)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel3)
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13))
                                            .addComponent(textaratareteta))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nextBtn)
                                            .addComponent(next2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(infometatImg, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel1)
                                                    .addComponent(minute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(intervaltimpSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)
                                                .addComponent(next3Btn))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(aratareteteBtn))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diabetImg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardiacImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vegetarianImg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientLogat)
                .addContainerGap())
        );

        jPanel3.setVisible(false);
        vegetarianImg.setVisible(false);
        cardiacImg.setVisible(false);
        diabetImg.setVisible(false);
        infometatImg.setVisible(false);
        intervaltimpSlider.setVisible(false);
        jPanel1.setVisible(false);
        jScrollPane1.setVisible(false);
        jLabel3.setVisible(false);
        next2Btn.setVisible(false);
        jLabel1.setVisible(false);
        minute.setVisible(false);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel5.setVisible(false);
        nextBtn.setVisible(false);
        textaratareteta.setVisible(false);
        jLabel7.setVisible(false);
        jLabel2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel5.setVisible(true);
        jLabel8.setVisible(false);
        aratareteteBtn.setVisible(false);
        next3Btn.setVisible(false);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 840, 552);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        nextBtn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void next3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next3BtnActionPerformed
        // TODO add your handling code here:
        if(intervaltimpSlider.getValue()==0) //daca nu s-a selectat timpul
        JOptionPane.showMessageDialog(this,"Nu ati selectat!");
        else// apare optiunea 4(ustensilele)
        {   
          
           int timpi=Integer.parseInt(jLabel1.getText());//luamusrrname-ul de la login
    
            jLabel8.setVisible(true);
            jPanel3.setVisible(true);
            aratareteteBtn.setVisible(true);

            //dispar imaginile corespunzatoare optiunii 1
            //pt a face loc optiunii nr. 4
            vegetarianImg.setVisible(false);
            cardiacImg.setVisible(false);
            infometatImg.setVisible(false);
            diabetImg.setVisible(false);
        }
    }//GEN-LAST:event_next3BtnActionPerformed

    private void aratareteteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aratareteteBtnActionPerformed
     
        String preferinta;
        if (diabeticRad.isSelected())
        preferinta="diabet";
        if (vegetarianRad.isSelected())
        preferinta="vegetarian";
        if (cardiacRad.isSelected())
        preferinta="cardiac";
        if (niciopreferintaRad.isSelected())
        preferinta="nimic";

        //nu a selectat nicio ustensila
        // isSelected()= true, daca butonul e selectat
        if(!merdeneaCheck.isSelected()&&!aragazCheck.isSelected()&&!cuptorCheck.isSelected()&&!tigaieCheck.isSelected()&&
            !bolCheck.isSelected()&&!mixerCheck.isSelected()&&!tocatorCheck.isSelected()&&!blenderCheck.isSelected()&&
            !robotdebucatarieCheck.isSelected()&&!paletaCheck.isSelected()&&!tavaCheck.isSelected()&&!telCheck.isSelected())
        JOptionPane.showMessageDialog(this,"Selectati cel putin o optiune!");
        //String afis="";
        //for (Component c: jPanel3.getComponents())
        //if (c.isEnabled())
        //      afis= afis+c;

        //String afis=listaingrediente.getSelectedValuesList().toString();
        // textaratareteta.setText(afis);

    }//GEN-LAST:event_aratareteteBtnActionPerformed

    private void textarataretetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textarataretetaActionPerformed
        //if (listaingrediente..isSelected())
        String afis=listaingrediente.getSelectedValuesList().toString();
        textaratareteta.setText(afis);

    }//GEN-LAST:event_textarataretetaActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed

        if(!diabeticRad.isSelected() && !vegetarianRad.isSelected() && !cardiacRad.isSelected() && !niciopreferintaRad.isSelected())
        JOptionPane.showMessageDialog(this,"Nu ati selectat!");
        else
        {
            //diabetImg.setVisible(false);
            // cardiacImg.setVisible(false);
            //infometatImg.setVisible(false);
            //vegetarianImg.setVisible(false);
            //jPanel1.setVisible(false);
            nextBtn.setVisible(false);
            listaingrediente.setVisible(true);
            jLabel3.setVisible(true);
            jScrollPane1.setVisible(true);
            next2Btn.setVisible(true);

            if (diabeticRad.isSelected()&& !vegetarianRad.isSelected() && !cardiacRad.isSelected() &&!niciopreferintaRad.isSelected())
            diabeticRad.setForeground(Color.green);
            if (cardiacRad.isSelected()&& !vegetarianRad.isSelected() && !diabeticRad.isSelected() &&!niciopreferintaRad.isSelected())
            cardiacRad.setForeground(Color.green);
            if (vegetarianRad.isSelected()&& !diabeticRad.isSelected() && !cardiacRad.isSelected() &&!niciopreferintaRad.isSelected())
            vegetarianRad.setForeground(Color.green);
            if (niciopreferintaRad.isSelected()&& !vegetarianRad.isSelected() && !cardiacRad.isSelected() &&!diabeticRad.isSelected())
            niciopreferintaRad.setForeground(Color.green);
        }

    }//GEN-LAST:event_nextBtnActionPerformed

    private void next2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2BtnActionPerformed
        // TODO add your handling code here:

        if(listaingrediente.isSelectionEmpty()) //daca nu am selectat nimic din lista de ingrediente
        JOptionPane.showMessageDialog(this,"Nu ati selectat!");
        else{
            //String afis=listaingrediente.getSelectedValuesList().toString();
            //textaratareteta.setText(afis);
            next2Btn.setVisible(false);
            jLabel7.setVisible(true);
            jLabel1.setVisible(true);
            minute.setVisible(true);
            intervaltimpSlider.setVisible(true);
            next3Btn.setVisible(true);
        }
    }//GEN-LAST:event_next2BtnActionPerformed

    private void niciopreferintaRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niciopreferintaRadActionPerformed
        // TODO add your handling code here:
        if (niciopreferintaRad.isSelected()) //daca acest buton e selectat
        vegetarianRad.setSelected(false); //NU poate fi selectat
        cardiacRad.setSelected(false); // -||-
        diabeticRad.setSelected(false);
        //ascund celelalte imagini atunci cand utilizatorul isi schimba preferinta
        vegetarianImg.setVisible(false);
        cardiacImg.setVisible(false);
        diabetImg.setVisible(false);
        // apare doar imaginea pt preferinta lui
        infometatImg.setVisible(true);
    }//GEN-LAST:event_niciopreferintaRadActionPerformed

    private void cardiacRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardiacRadActionPerformed
        // TODO add your handling code here:
        if (cardiacRad.isSelected()) //daca e selectat acest buton=> celelalte NU mai pot fi selectate
            System.out.println(cardiacRad.getText());
        vegetarianRad.setSelected(false); //NU poate fi selectat
        diabeticRad.setSelected(false); // -||-
        niciopreferintaRad.setSelected(false);
        //ascund celelalte imagini atunci cand utilizatorul isi schimba preferinta
        vegetarianImg.setVisible(false);
        diabetImg.setVisible(false);
        infometatImg.setVisible(false);
        // apare doar imaginea pt preferinta lui
        cardiacImg.setVisible(true);
    }//GEN-LAST:event_cardiacRadActionPerformed

    private void vegetarianRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetarianRadActionPerformed
        // TODO add your handling code here:
        if (vegetarianRad.isSelected()) //daca e selectat acest buton=> celelalte NU mai pot fi selectate
        diabeticRad.setSelected(false); //NU poate fi selectat
        cardiacRad.setSelected(false); // -||-
        niciopreferintaRad.setSelected(false);
        //ascund celelalte imagini atunci cand utilizatorul isi schimba preferinta
        diabetImg.setVisible(false);
        cardiacImg.setVisible(false);
        infometatImg.setVisible(false);
        // apare doar imaginea pt preferinta lui
        vegetarianImg.setVisible(true);
    }//GEN-LAST:event_vegetarianRadActionPerformed

    private void diabeticRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabeticRadActionPerformed
        // TODO add your handling code here:
        /*   if(vegetarianRad.isSelected()||niciopreferintaRad.isSelected()||cardiacRad.isSelected())
        {
            vegetarianRad.setColor(Color.black);
            cardiacRad.setColor(Color.black);
            niciopreferintaRad.setColor(Color.black);
        }
        */
        if (diabeticRad.isSelected()) //daca e selectat acest buton=> celelalte NU mai pot fi selectate
         
        vegetarianRad.setSelected(false); //NU poate fi selectat
        cardiacRad.setSelected(false); // -||-
        niciopreferintaRad.setSelected(false);
        //ascund celelalte imagini atunci cand utilizatorul isi schimba preferinta
        vegetarianImg.setVisible(false);
        cardiacImg.setVisible(false);
        infometatImg.setVisible(false);
        // apare doar imaginea pt preferinta lui
        diabetImg.setVisible(true);
    }//GEN-LAST:event_diabeticRadActionPerformed

    private void intervaltimpSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intervaltimpSliderStateChanged
        jLabel1.setText(Integer.toString(intervaltimpSlider.getValue()));
        
        
       
       
        
        
        
        
    }//GEN-LAST:event_intervaltimpSliderStateChanged

    private void telCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telCheckActionPerformed

    private void robotdebucatarieCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robotdebucatarieCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_robotdebucatarieCheckActionPerformed

    private void merdeneaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merdeneaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merdeneaCheckActionPerformed

    private void aratareteteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aratareteteBtnMouseClicked
        // TODO add your handling code here:
       ReteteForm x=new ReteteForm();
      // LoginForm y=new LoginForm();
      //FARA ASTA NU SE VEDE NIMIC in RETETEFORM!!!!!!!!!!!!!!!!!
       x.setVisible(true);
       x.pack();
       x.setLocationRelativeTo(null);
       x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();//ca sa dispara Loginformu-ul din spate
   
       //Vrem sa vedem daca utilizatorul este logat sau nu=>ca sa stim cate retete "aratam" utilizatorului
      if(clientLogat.getText().equals("clicked"))//daca utilizatorul e logat=>arat mai multe retete
      {
          int contor=0;//in acest contor tin nr de retete pe care vreau sa le afisez   
          int timp=Integer.parseInt(jLabel1.getText());
          
        try
        {
        Connection conn=null;
        conn=DriverManager.getConnection("jdbc:mysql://localhost/database_try","root","");
        System.out.println("connected2");
        String query="";///query trebuie neaparat declarata aici, altfel=>EROARE!!!
        if(diabeticRad.isSelected()==true) 
          query="SELECT * from retete_d WHERE timp_preparare=?";
        else if(vegetarianRad.isSelected()) 
          query="SELECT * from retete_v WHERE timp_preparare=?";
        else if(cardiacRad.isSelected()) 
          query="SELECT * from retete_c WHERE timp_preparare=?";
        else if(niciopreferintaRad.isSelected()) 
          query="SELECT * from retete_tot WHERE timp_preparare=?";
        
        
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs;
           
        ps.setInt(1,timp);
        rs=ps.executeQuery();
        int ok=0;
        x.retete.setText(null);
        while(rs.next()==true&&contor<2)
            {  
            String ingrediente_client="capsuni,iaurt,zahar pudra,fulgi de ciocolata,gff,grd";
            String[]ingrediente_clientf=ingrediente_client.split(",");
            String str=rs.getString("ingrediente");
            String[]ingrediente_bd=str.split(",");
            int c=0;
            for(int i=0;i<ingrediente_clientf.length;i++)
            {
                     
                for(int j=0;j<ingrediente_bd.length;j++)
                {
                    if(ingrediente_clientf[i].equals((ingrediente_bd[j])))
                    c++;
                }
            }
            if(c>=ingrediente_bd.length)
            {
                ok=1;
                x.retete.setVisible(true);
                x.retete.append("INGREDIENTE : \n\n"+rs.getString("ingrediente")+" \n\n");
                x.retete.append("  "+rs.getString("titlu").toUpperCase()+" : \n\n"+rs.getString("mod_preparare")+" \n\n");
                
            }
           }
             
        if(ok==0)///daca nu am gasit nicio reteta in BD care sa corespunda timpului introdus de utilizator
        {
                  x.retete.append("Nu exista retete corespunzatoare");
        }
              
        conn.close();
        }catch(SQLException e){System.err.println(e);}  
           
      }
      else //daca utilizatorul nu e logat
      {
         
           int timp=Integer.parseInt(jLabel1.getText());
            
          
        try
        {
        Connection conn=null;
        conn=DriverManager.getConnection("jdbc:mysql://localhost/database_try","root","");
        System.out.println("connected2");
        String query="";///query trebuie neaparat declarata aici, altfel=>EROARE!!!
        if(diabeticRad.isSelected()==true) 
          query="SELECT * from retete_d WHERE timp_preparare=?";
        else if(vegetarianRad.isSelected()) 
          query="SELECT * from retete_v WHERE timp_preparare=?";
        else if(cardiacRad.isSelected()) 
          query="SELECT * from retete_c WHERE timp_preparare=?";
        else if(niciopreferintaRad.isSelected()) 
          query="SELECT * from retete_tot WHERE timp_preparare=?";
        
        
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs;
           
        ps.setInt(1,timp);
        rs=ps.executeQuery();
        int ok=0;
        x.retete.setText(null);
        while(rs.next()==true)
            {  
            
            String ingrediente_client="capsuni,iaurt,zahar pudra,fulgi de ciocolata,gff,grd";
            String[]ingrediente_clientf=ingrediente_client.split(",");
            String str=rs.getString("ingrediente");
            String[]ingrediente_bd=str.split(",");
            int c=0;
            for(int i=0;i<ingrediente_clientf.length;i++)
            {
                     
                for(int j=0;j<ingrediente_bd.length;j++)
                {
                    if(ingrediente_clientf[i].equals((ingrediente_bd[j])))
                    c++;
                }
            }
            if(c>=ingrediente_bd.length)
            {
                ok=1;
                x.retete.setVisible(true);
                x.retete.append("INGREDIENTE : \n\n"+rs.getString("ingrediente")+" \n\n");
                x.retete.append("  "+rs.getString("titlu").toUpperCase()+" : \n\n"+rs.getString("mod_preparare")+" \n\n");
                
            }
                
           }
             
        if(ok==0)///daca nu am gasit nicio reteta in BD care sa corespunda timpului introdus de utilizator
        {
                  x.retete.append("Nu exista retete corespunzatoare");
        }
              
        conn.close();
        }catch(SQLException e){System.err.println(e);}  
           
      }

       

    }//GEN-LAST:event_aratareteteBtnMouseClicked

    private void mixerCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixerCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixerCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
        //NewJFrame frame=new NewJFrame();
        //frame.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aragazCheck;
    private javax.swing.JButton aratareteteBtn;
    private javax.swing.JCheckBox blenderCheck;
    private javax.swing.JCheckBox bolCheck;
    private javax.swing.JLabel cardiacImg;
    private javax.swing.JRadioButton cardiacRad;
    public javax.swing.JLabel clientLogat;
    private javax.swing.JCheckBox cuptorCheck;
    private javax.swing.JLabel diabetImg;
    private javax.swing.JRadioButton diabeticRad;
    private javax.swing.JLabel girl;
    private javax.swing.JLabel infometatImg;
    private javax.swing.JSlider intervaltimpSlider;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaingrediente;
    private javax.swing.JCheckBox merdeneaCheck;
    private javax.swing.JTextField minute;
    private javax.swing.JCheckBox mixerCheck;
    private javax.swing.JButton next2Btn;
    private javax.swing.JButton next3Btn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton niciopreferintaRad;
    private javax.swing.JCheckBox paletaCheck;
    private javax.swing.JCheckBox robotdebucatarieCheck;
    private javax.swing.JCheckBox tavaCheck;
    private javax.swing.JCheckBox telCheck;
    private javax.swing.JTextField textaratareteta;
    private javax.swing.JCheckBox tigaieCheck;
    private javax.swing.JCheckBox tocatorCheck;
    private javax.swing.JLabel vegetarianImg;
    private javax.swing.JRadioButton vegetarianRad;
    // End of variables declaration//GEN-END:variables
}
