
import com.sun.istack.internal.logging.Logger;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import javax.swing.*;
import javax.swing.JOptionPane;

import java.awt.*;
import java.awt.event.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    private static final String conn_string="jdbc:mysql://127.0.0.1/java_login_register";
    //private static final String conn_string="jdbc:mysql://192.168.0.100/phpmyadmin/java_login_register";
    //192.168.0.100/phpmyadmin//java_login_register";
    //private static final String FNAME="root";
   // private static final String LNAME="root";
  //   private static final String UNAME="root";
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        min_btn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlabel_fn = new javax.swing.JLabel();
        jLabel_ln = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_retype_pass = new javax.swing.JLabel();
        jLabel_birth_date = new javax.swing.JLabel();
        jln = new javax.swing.JTextField();
        jfn = new javax.swing.JTextField();
        jPassword_field = new javax.swing.JPasswordField();
        cancel_btn = new javax.swing.JButton();
        register_btn_c = new javax.swing.JButton();
        jUsername_field = new javax.swing.JTextField();
        jRegister = new javax.swing.JLabel();
        jRePassword_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(620, 670));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Register");

        close_btn.setBackground(new java.awt.Color(0, 0, 0));
        close_btn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        close_btn.setText("X");
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });

        min_btn.setBackground(new java.awt.Color(0, 0, 0));
        min_btn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        min_btn.setText("-");
        min_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_btn)
                    .addComponent(min_btn))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jlabel_fn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlabel_fn.setText("First Name:");

        jLabel_ln.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_ln.setText("Last Name:");

        jLabel_username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_username.setText("Username:");

        jLabel_password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_password.setText("Password:");

        jLabel_retype_pass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_retype_pass.setText("Retype Pass:");

        jLabel_birth_date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_birth_date.setText("Birth Date:");

        jln.setBackground(new java.awt.Color(102, 102, 102));
        jln.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jln.setForeground(new java.awt.Color(255, 255, 255));
        jln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlnActionPerformed(evt);
            }
        });

        jfn.setBackground(new java.awt.Color(102, 102, 102));
        jfn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jfn.setForeground(new java.awt.Color(255, 255, 255));
        jfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfnActionPerformed(evt);
            }
        });

        jPassword_field.setBackground(new java.awt.Color(102, 102, 102));
        jPassword_field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPassword_field.setForeground(new java.awt.Color(255, 255, 255));
        jPassword_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_fieldActionPerformed(evt);
            }
        });

        cancel_btn.setBackground(new java.awt.Color(255, 0, 0));
        cancel_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        register_btn_c.setBackground(new java.awt.Color(0, 0, 255));
        register_btn_c.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        register_btn_c.setText("Register");
        register_btn_c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btn_cActionPerformed(evt);
            }
        });

        jUsername_field.setBackground(new java.awt.Color(102, 102, 102));
        jUsername_field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jUsername_field.setForeground(new java.awt.Color(255, 255, 255));
        jUsername_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsername_fieldActionPerformed(evt);
            }
        });

        jRegister.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRegister.setText("    click here to login");
        jRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegisterMouseClicked(evt);
            }
        });

        jRePassword_field.setBackground(new java.awt.Color(102, 102, 102));
        jRePassword_field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRePassword_field.setForeground(new java.awt.Color(255, 255, 255));
        jRePassword_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRePassword_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_birth_date, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(register_btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jfn, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jln)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_retype_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPassword_field, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRePassword_field, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jUsername_field, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(52, 52, 52))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsername_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPassword_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_retype_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRePassword_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel_birth_date, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_btnMouseClicked

    private void min_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_min_btnMouseClicked

    private void jlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlnActionPerformed

    private void jfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfnActionPerformed

    private void jPassword_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_fieldActionPerformed

    private void jUsername_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsername_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsername_fieldActionPerformed
//Functia de mai jos se va apela cand se va apasa pe jLabel-ul jRegister care are textul: click here to login
//in aceasta functie se creeaza o instanta pt obiectul LoginForm pt a face legatura cu Interfata de logare  
    private void jRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();//ca sa dispara Loginformu-ul din spate
    }//GEN-LAST:event_jRegisterMouseClicked
//in functia de mai jos se realizeaza partea efectiva de inregistrare a utilizatorului
//si de validare a datelor introduse de acestea=>sa nu fie campuri empty, sa corespunda parolele(password si rewrite password)
   
    private void register_btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btn_cActionPerformed
        String fname =jfn.getText();
        String lname = jln.getText();
        String uname =jUsername_field.getText();
        String pass=String.valueOf(jPassword_field.getPassword());
        String re_pass=String.valueOf(jRePassword_field.getPassword());
        
        if(checkUsername(uname))
        {
             JOptionPane.showMessageDialog(null,"This Username Already Exist");
        }
        else if(fname.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Add a FirstName");
        }
        else if(lname.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Add a LastName");
        }
        else if(uname.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Add a UserName");
        }
        
        else if(pass.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Add a password");
        }
        else if(!pass.equals(re_pass))
        {
             JOptionPane.showMessageDialog(null,"Retype the password again");
        }
        
        
       else
        {
        
       /**varianta asta mergee, yeeey CONEXIUNE LA BD*/
        Connection conn=null;
        try
        {
            conn=DriverManager.getConnection(conn_string,"root","");
            System.out.println("connected");
            Statement stmt=(Statement)conn.createStatement();
            String insert="INSERT INTO the_app_users(user_fname, user_lname,username,password,retype_password) VALUES (?,?,?,?,?)";
            
            PreparedStatement ps = conn.prepareStatement(insert);
            ps.setString(1, fname);
            ps.setString(2, lname);
            ps.setString(3, uname);
            ps.setString(4, pass);
            ps.setString(5, re_pass);
           
      
           // ps.execute();s-ar mai executa o data , si la if-ul de mai jos se executa
            
            if(ps.executeUpdate()>0)//se insereaza in baza de date si aici 0 data
            {
                JOptionPane.showMessageDialog(null,"New User Add");
            }
            
            ps.close();
            conn.close();
            
            //stmt.executeUpdate(insert);
        }catch(SQLException e){System.err.println(e);}
        
        }
 

    }//GEN-LAST:event_register_btn_cActionPerformed

    private void jRePassword_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRePassword_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRePassword_fieldActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
     System.exit(0);        
        
    }//GEN-LAST:event_cancel_btnActionPerformed
  ///verificam daca username-ul introduc de utilizator deja exista in baza de date
    public boolean checkUsername(String username)
    {
       //presupunem ca username-ul nu exista in baza de date
       boolean checkUser=false;
        try
        {
        Connection conn=null;
        //conn=DriverManager.getConnection("jdbc:mysql://localhost/java_login_register","root","");
        conn=DriverManager.getConnection("jdbc:mysql://192.168.0.101/phpmyadmin/java_login_register","root","");
        System.out.println("connected3");
        String query="SELECT * from the_app_users WHERE username=?";
      
    
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs;
            
        ps.setString(1, username);
       
        rs=ps.executeQuery();
        //daca gasim userame-ul variabila booleana se face true
        if(rs.next())
        {
          
        checkUser=true;
         }
             
      
        conn.close();
            
        }catch(SQLException e){System.err.println(e);}
        
        
       return checkUser; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel close_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_birth_date;
    private javax.swing.JLabel jLabel_ln;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_retype_pass;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword_field;
    private javax.swing.JPasswordField jRePassword_field;
    private javax.swing.JLabel jRegister;
    private javax.swing.JTextField jUsername_field;
    private javax.swing.JTextField jfn;
    private javax.swing.JLabel jlabel_fn;
    private javax.swing.JTextField jln;
    private javax.swing.JLabel min_btn;
    private javax.swing.JButton register_btn_c;
    // End of variables declaration//GEN-END:variables
}
